name: Scheduled deployment
on:
#   schedule: # Run workflow automatically
#     - cron: '0 */8 * * *' # Runs every 4 hours, on the hour
  workflow_dispatch:
  
jobs:
  DeploySite:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy site to Netlify
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: netlify
          netlify_deploy_hook_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
