name: Deploy static site
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "2 5,13,21 * * *"

jobs:
  DeploySite:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy site
        uses: lwojcik/github-action-deploy-static-site@v1
        with:
          platform: vercel
          vercel_deploy_hook_url: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
          always_deploy: true
